services:
  - type: web
    name: hrms-lite-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hrms_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: hrms-lite-db
    databaseName: hrms_lite
    user: hrms_lite
